name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm" # Set this to npm, yarn or pnpm.

      - name: Install frontend dependencies
        run: npm ci # Change this to npm ci, yarn install --frozen-lockfile or pnpm install --frozen-lockfile.

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
